#!/bin/bash

# 测试 macOS 右键菜单打开文件的行为
echo "🔍 测试 macOS 右键菜单打开文件行为"
echo "======================================"

# 模拟不同的文件打开场景
echo ""
echo "1. 🍎 macOS 典型右键菜单参数:"
echo "   - 直接打开文件: /path/to/file.md"
echo "   - 通过 file:// URL: file:///path/to/file.md"
echo "   - URL 编码空格: file:///path/to/my%20file.md"
echo "   - 中文文件名: file:///path/to/中文文件.md"
echo "   - 带程序序列号: -psn_0_123456 /path/to/file.md"

echo ""
echo "2. 🔧 常见问题排查:"
echo "   a) 检查文件关联是否正确注册"
echo "      defaults read com.apple.LaunchServices/com.apple.launchservices.secure"
echo "      | grep -A 5 -B 5 \"markedit\""
echo ""
echo "   b) 检查 Info.plist 文件类型声明"
echo "      plutil -p ./src-tauri/target/release/bundle/macos/MarkEdit.app/Contents/Info.plist"
echo "      | grep -A 10 -B 10 \"CFBundleDocumentTypes\""
echo ""
echo "   c) 手动测试文件关联"
echo "      open -a MarkEdit /path/to/test.md"
echo ""
echo "   d) 查看系统日志"
echo "      log show --predicate 'subsystem contains \"MarkEdit\"' --last 1h"

echo ""
echo "3. 🛠️ 修复步骤:"
echo "   a) 重新注册文件关联"
echo "      /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
echo "      -f ./src-tauri/target/release/bundle/macos/MarkEdit.app"
echo ""
echo "   b) 重建应用"
echo "      npm run tauri:build"
echo ""
echo "   c) 清除启动服务缓存"
echo "      /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
echo "      -kill -r -domain local -domain system -domain user"
echo ""
echo "   d) 重启 Finder"
echo "      killall Finder"

echo ""
echo "4. 📝 测试命令:"
echo "   # 测试简单文件打开"
echo "   ./markedit-tauri/target/release/markedit-tauri /path/to/test.md"
echo ""
echo "   # 测试 file:// URL"
echo "   ./markedit-tauri/target/release/markedit-tauri file:///path/to/test.md"
echo ""
echo "   # 查看 Rust 后端输出"
echo "   RUST_LOG=info ./markedit-tauri/target/release/markedit-tauri /path/to/test.md"

echo ""
echo "5. 💡 macOS 特定注意事项:"
echo "   - macOS App Sandbox 可能限制文件访问"
echo "   - 需要正确的 entitlements 配置"
echo "   - 第一次打开可能需要用户授权"
echo "   - 文件关联注册可能需要重启"

echo ""
echo "6. 🎯 关键检查点:"
echo "   - Rust 后端是否收到文件路径参数"
echo "   - 参数格式是否正确（file:// 解码等）"
echo "   - 文件路径是否被正确识别"
echo "   - 前端是否收到文件路径"
echo "   - 文件是否可读"

echo ""
echo "✅ 测试脚本完成"
echo "运行应用后，查看 Rust 控制台输出和浏览器控制台日志"